/*branch development_1*/
Select * from SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
union all
Select * from SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
union all
Select * from SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
